resources:
  - name: repo-master
    type: git
    source: { uri: 'https://github.com/nevenc-pivotal/simple-boot.git', branch: 'master' }
    check_every: 10s # for demo
jobs:
  - name: unit-test
    serial: true
    public: true
    plan:
      - get: repo-master
        trigger: true
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: java, tag: 8-alpine }
          inputs:
            - name: repo-master
          run:
            path: sh
            args:
              - -c
              - |
                cd repo-master
                ./mvnw test
